export const CLIENT_REGISTER_LOADING = 'CLIENT_REGISTER_LOADING';
export const CLIENT_REGISTER_SUCCESS = 'CLIENT_REGISTER_SUCCESS';
export const CLIENT_REGISTER_FAILED = 'CLIENT_REGISTER_FAILED';

export const CLIENT_LOGIN_LOADING = 'CLIENT_LOGIN_LOADING';
export const CLIENT_LOGIN_SUCCESS = 'CLIENT_LOGIN_SUCCESS';
export const CLIENT_LOGIN_FAILED = 'CLIENT_LOGIN_FAILED';

export const CLIENT_LOGOUT = 'CLIENT_LOGOUT';

