export const COMMAND_LIST_REQUEST = 'COMMAND_LIST_REQUEST';
export const COMMAND_LIST_SUCCESS = 'COMMAND_LIST_SUCCESS';
export const COMMAND_LIST_FAILED  = 'COMMAND_LIST_FAILED';


export const ADD_COMMAND_REQUEST = 'ADD_COMMAND_REQUEST';
export const ADD_COMMAND_SUCCESS = 'ADD_COMMAND_SUCCESS';
export const ADD_COMMAND_FAILED  = 'ADD_COMMAND_FAILED';


export const UPDATE_COMMAND_REQUEST = 'UPDATE_COMMAND_REQUEST';
export const UPDATE_COMMAND_SUCCESS = 'UPDATE_COMMAND_SUCCESS';
export const UPDATE_COMMAND_FAILED  = 'UPDATE_COMMAND_FAILED';


export const DELETE_COMMAND_REQUEST = 'DELETE_COMMAND_REQUEST';
export const DELETE_COMMAND_SUCCESS = 'DELETE_COMMAND_SUCCESS';
export const DELETE_COMMAND_FAILED  = 'DELETE_COMMAND_FAILED';